### PR TITLE
Fix generated constructor for FirebaseValue class

### PR DESCRIPTION
**Pull request by kmenager**
Fix constructor for FirebaseValue class where constructor  parameters name is the same as variable for List and Map object

### CODE REVIEW

**Comment by kmenager** [comment]
@mattlogan any idea for a new version with this PR ?

**Comment by mattlogan** [comment]
Does this actually fix an issue that you're having? Or is this just a syntax improvement?

**Comment by kmenager** [comment]
I fix it with test

**Comment by mattlogan** [comment]
I don't think this PR is necessary, and I'm okay with the generated syntax as it is right now. Thanks!

**Comment by mattlogan** [comment]
Oh, I see the issue now. If you had a list or map that had the same name as the type of the AutoValue class, this would cause an error. Sorry I missed that!

**Comment by mattlogan** [comment]
Thanks for the fix. I'll make a release within the next couple days.

**Comment by kmenager** [comment]
Yes, I'm sorry for my poor explication.
Thanks for the merged and for this library.

**Pull request merged**
